server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Automatically create routes based on service ID (optional but cool)
          lower-case-service-id: true
      routes:
        # Route 1: Auth Service (Dynamic)
        - id: auth-service
          uri: lb://AUTH-SERVICE  # <--- MAGIC CHANGE: Use the Service Name!
          predicates:
            - Path=/api/v1/auth/**

        # Route 2: Video Service (Dynamic)
        - id: video-service
          uri: lb://VIDEO-SERVICE # <--- MAGIC CHANGE
          predicates:
            - Path=/api/v1/videos/**
          filters:
            - AuthenticationFilter

        # Route 3: Swagger (Dynamic)
        - id: video-swagger
          uri: lb://VIDEO-SERVICE
          predicates:
            - Path=/v3/api-docs/**, /swagger-ui/**, /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/