server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Route 1: Auth Service (Public - No Filter needed)
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

        # Route 2: Video Service (PROTECTED - Add Filter)
        - id: video-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/videos/**
          filters:
            - AuthenticationFilter # <--- The Bouncer is now watching this door!

        # Route 3: Swagger (Public)
        - id: video-swagger
          uri: http://localhost:8082
          predicates:
            - Path=/v3/api-docs/**, /swagger-ui/**, /swagger-ui.html